### ISSUE TITLE
Experimenting with Archiving older GregTech Versions using this Repo

### ISSUE THREAD

**Issue by GregoriusT** [GregTech6/GregTech0#1]
https://github.com/GregTech6/GregTech0/releases/tag/v1.0.0

Since I cant comment on a Release, this will have to do. I'm trying to learn how to do this Stuff properly. There is going to be Project Pages for GT1 to GT5 each too once I am ready.

This effort started because @Prospector has contacted me about this, and how it is better to have GitHub Releases for Launchers too instead of ONLY my own Website. ^^

Any Questions/Comments? (Not that I expect many people to answer this)

**Comment by GregoriusT** [comment]
Okay progress was made on the 5 new Projects, but I did not put the Releases yet.

https://github.com/GregTech6/GregTech1
https://github.com/GregTech6/GregTech2
https://github.com/GregTech6/GregTech3
https://github.com/GregTech6/GregTech4
https://github.com/GregTech6/GregTech5

Edit: Ctrl+Enter apparently posts the Comment right away, which is dumb if you spam Ctrl+V and Enter multiple times in a row.

**Comment by GregoriusT** [comment]
Okay @Prospector I think everything is ready now. Each GregTech Project has a Release for each supported MC Version containing all content I had for said MC Version, which should make it work with the Launcher.

Please tell me if it works or if I did anything wrong. ^^

**Comment by Prospector** [comment]
Great to hear, looks setup nicely. Thanks for doing this!
